config/routes.rb
Rails.application.routes.draw do
  
  resources :instruments

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'pages#index'
	resources :users, only: [:show]

	get 'matelpage/index' => 'matelpage#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	belongs_to :user

	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :instrument


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:phone_number,:description,:sex,:age,:instrument,:sonoligoid])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/matelpage_controller.rb
class MatelpageController < ApplicationController

	def index
		
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@user = User.all
  	#大文字のUserはモデル名。.allは全ての情報を引っ張ってくるメソッド
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	#変数はアクションで定義 参考 http://prog-8.com/slides?displayed_id=2759&lesson=70%2C74%2C76%2C77%2C82%2C89%2C86%2C96%2C92%2C93%2C107%2C90%2C95%2C102%2C111&word=%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3
  	
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/matelpage_helper.rb
module MatelpageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/instruments/create.html.erb
<h1>Instruments#create</h1>
<p>Find me in app/views/instruments/create.html.erb</p>

app/views/instruments/edit.html.erb
<h1>Instruments#edit</h1>
<p>Find me in app/views/instruments/edit.html.erb</p>

app/views/instruments/index.html.erb
<h1>Instruments#index</h1>
<p>Find me in app/views/instruments/index.html.erb</p>

app/views/instruments/new.html.erb
<h1>Instruments#new</h1>
<p>Find me in app/views/instruments/new.html.erb</p>

app/views/instruments/show.html.erb
<h1>Instruments#show</h1>
<p>Find me in app/views/instruments/show.html.erb</p>

app/views/instruments/update.html.erb
<h1>Instruments#update</h1>
<p>Find me in app/views/instruments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railspractice20180303</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      
      
<!-- To be able to use these icons, you must include this line in the <head>portion of your HTML code -->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!-- Flashにメッセージがあるとき -->
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
            toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/js/materialize.min.js"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
 <%= render 'partial/navbar'%>

	<div class="container">
		<div class="row">
			<div class="col s12">
				  <h1 class="display-3 center-align">SonoLigo</h1>
					<div class="row">
					  <% @user.each do |person|%>
					  	
				        <div class="col s12 m4">
				          <div class="card blue-grey darken-1">
				            <div class="card-content white-text">
				              <span class="card-title">
				              	<!-- 名前 -->
				              	<%= person.name %>
			              	</span>
			              	<!-- 性別 -->
			              		<span>性別: <%= person.sex %></span>
			              		<span>楽器 :<%= person.instrument %></span>
			              		
				              	<!-- 自己紹介 -->
				              	<div>
				             	 	<%= person.description %>
				             	 </div>
				            </div>
				            <div class="card-action">
				              <a href="#">プロフィールを見る</a>
				              <a href="#">音源を聞く</a>
				            </div>
				          </div>
				        </div>
				    <% end %>	
			   	</div>
				  	
				  			
			</div>
		</div>
	</div>	




</div>


<script type="text/javascript">
	$(function(){
		$(".navbar").removeClass("navbar-devise");
		$(".navbar").addClass("navbar-default");
	});
</script>

app/views/partial/_deviseErrorMsg.html.erb
<!-- deviseにエラーがある場合 -->
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="blue darken-3">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">SonoLigo</a>

    <!-- PC用メニュー -->
    <ul class="right hide-on-med-and-down">
      <% if (!user_signed_in?) %>
          <!-- ログインしていない時 -->
            <li><%= link_to "先生になる" ,new_user_registration_path %></li>
            <li><%= link_to "ログイン" ,user_session_path %></li>
          <% else %>
            <!-- ログインしている時 -->
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.email %> <span class="caret"></span></a></li>
              <ul id= "dropdown1" class='dropdown-content'>
                <li><%= link_to "プロフィール",user_path(current_user) %></li>
                <li><%= link_to "プロフィールを編集",edit_user_registration_path %></li>
                <li><%= link_to "楽器を登録", new_instrument_path %></li>
                <li><%= link_to "ログアウト" ,destroy_user_session_path,method: :delete %></li>  
              </ul>
            
            
          <% end %>
    </ul>


    <!-- スマホ、タブレット用メニュー -->
    <ul class="right show-on-medium-and-down hide-on-med-and-up">
      <% if (!user_signed_in?) %>
          <!-- ログインしていない時 -->
            <li><a href ="#" class="dropdown-trigger" data-target="dropdown2"><i class="material-icons">dehaze</i></a></li>
            <ul id="dropdown2" class="dropdown-content">
            <li><%= link_to "先生になる" ,new_user_registration_path %></li>
            <li><%= link_to "ログイン" ,user_session_path %></li>
            </ul>
          <% else %>
            <!-- ログインしている時 -->
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown3"><i class="material-icons">dehaze  </i> </a></li>
              <ul id= "dropdown3" class='dropdown-content'>
                <li><%= link_to "プロフィール",user_path(current_user) %></li>
                <li><a href="#">楽器を登録</a></li>
                <li><%= link_to "ログアウト" ,destroy_user_session_path,method: :delete %></li>  
              </ul>
            
            
          <% end %>
    </ul>

  </div>
</nav>

<script>
 $('.dropdown-trigger').dropdown();
</script>

app/views/users/show.html.erb
<%= render 'partial/navbar' %>

<div class="container">
	<div class="row">
		<div class="col m4 col l3">
			<div class="user-profile row-space-4 center-align">
				
			</div>
			<div class="panel panel-default verifications hidden-xs hidden-sm">
				<div class="panel-heading">
					認証済みID
				</div>
				<div class="panel-body">
					<div id="ver-email">
						メールアドレス
					</div>
					<br>
					<div id="ver-tel">
						電話番号
					</div>
					<br>
					<div id="ver-facebook">
						Facebook
					</div>
				</div>
			</div>
		</div>

		<div class="col m8">
			<h1>こんにちわ</h1>
		</div>
	</div>  	
</div>